server: 
  port: 7001 #注册中心占用7001端口

spring: 
  application:
    name: microservicecloud-config-eureka-client

eureka: 
  instance:
    hostname: eureka7001.com
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/